### ISSUE TITLE
Chex Quest Support for IPXSetup?

### ISSUE THREAD

**Issue by OpenRift412** [fragglet/vanilla-utilities#10]
I think it could be a really neat experiment to have Chex Quest compatibility with IPXSetup, since the levels in the IWAD even come with deathmatch starts.

**Comment by fragglet** [comment]
This should already work. Please let me know if it doesn't.

```
ipxsetup -nodes 3 chex.exe -warp 1
```
or similar

**Comment by OpenRift412** [comment]
> This should already work. Please let me know if it doesn't.
> 
> ```
> ipxsetup -nodes 3 chex.exe -warp 1
> ```
> 
> or similar

yeah, that works, thanks. A shame it doesn't work with those Deathmanager configs you made.
