### ISSUE TITLE
Suggestion: Bringing Chocolate Doom's sync code to IPXSETUP

### ISSUE THREAD

**Issue by OpenRift412** [fragglet/vanilla-utilities#9]
Not really as must, as I understand this would likely be a significantly time-consuming task, but I think it would be interesting to see Chocolate Doom's sync code implemented into IPXSETUP, as it could really be a game-changer for long-distance play and/or varying connection qualities, moreso than `-extratics` and `-dup`. To maintian vanilla compatibility, the new sync code could probably coexist alongside the vanilla code, toggleable with a parameter like `-newnet`. Just something I thought I'd bring up here.

**Comment by fragglet** [comment]
Changing description to better match what I understand you to be proposing.

I agree that it would be a very nice feature to get better synchronization between players in vanilla Doom. However there are a couple of catches:

1. -newsync keeps players in sync by speeding up/slowing down the game timer and it's not obvious how that might be made to work under DOS. It also uses a more precise timer than is typically available under DOS machines - O(milliseconds)
1. Vanilla Doom itself has its own sync code that would potentially conflict.

I'm going to call this technically infeasible for now, though I don't discount the possibility that I or someone cleverer than me may prove me wrong in the future.
